[profile.default]
src = "contracts"
test = "contracts/integration/test"
out = "out"
libs = ["vendor/midnight/lib"]
via_ir = true
optimizer = true
optimizer_runs = 466
bytecode_hash = "none"
evm_version = "osaka"
solc_version = "0.8.34"

remappings = [
    "forge-std/=vendor/midnight/lib/forge-std/src/",
    "midnight/=vendor/midnight/src/",
]

[profile.default.fmt]
wrap_comments = true
