/**
 * Proves the pinned Midnight release still compiles to the exact bytecode Kyrve deployed.
 *
 * This is what makes `bytecode_hash = "none"` in the pinned foundry profile worth having: with
 * metadata stripped, compiled output is a pure function of (source, compiler, settings), so a
 * recompilation that differs by a single byte means one of those three changed. Without this
 * check, "we deployed the pinned release unmodified" would be a claim rather than a fact.
 *
 * It also compares against the runtime code actually on chain, when a deployment manifest exists,
 * so a substituted core is caught rather than assumed away.
 */

import { createHash } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";

import { readJson, repoPath, run, stableStringify } from "../lib/shell.js";

interface BytecodeLock {
  $comment: string;
  release: string;
  commit: string;
  compiler: Record<string, unknown>;
  contracts: Record<
    string,
    { creationCodeHash: string; runtimeCodeHash: string; runtimeSizeBytes: number }
  >;
}

const LOCK_PATH = repoPath("deployments/midnight-bytecode-lock.json");

/** Contracts whose bytecode is load-bearing for Kyrve. */
// Referenced by bare contract name: Midnight is reached through a remapping and lives outside
// `src`, so a path-qualified identifier does not resolve.
const TRACKED = [
  "Midnight",
  "KyrveOsakaProbe",
  "KyrveProtocolRegistry",
  "KyrveDeploymentVerifier",
  "KyrveExactFillVault",
  "KyrveQuoteRatifier",
] as const;

function sha256(hex: string): string {
  const body = hex.startsWith("0x") ? hex.slice(2) : hex;
  return createHash("sha256").update(Buffer.from(body, "hex")).digest("hex");
}

/**
 * `forge inspect <contract> <field>` emits a bare hex string, not JSON — including under `--json`,
 * where the output is unquoted and therefore not parseable. It is read as raw text.
 */
function inspect(contract: string, field: "bytecode" | "deployedBytecode"): string {
  const raw = run("forge", ["inspect", contract, field]).stdout.trim();
  if (!/^0x[0-9a-fA-F]*$/.test(raw)) {
    throw new Error(
      `forge inspect ${contract} ${field} did not return hex bytecode. Received: ${raw.slice(0, 120)}`,
    );
  }
  if (raw === "0x") {
    throw new Error(
      `${contract} has empty ${field}; it may be an interface or an abstract contract`,
    );
  }
  return raw;
}

function build(): BytecodeLock {
  const vendor = readJson<{ release: string; commit: string; compiler: Record<string, unknown> }>(
    repoPath("vendor-lock.json"),
  );

  const contracts: BytecodeLock["contracts"] = {};
  for (const name of TRACKED) {
    const creation = inspect(name, "bytecode");
    const runtime = inspect(name, "deployedBytecode");
    contracts[name] = {
      creationCodeHash: sha256(creation),
      runtimeCodeHash: sha256(runtime),
      runtimeSizeBytes: runtime.replace(/^0x/, "").length / 2,
    };
  }

  return {
    $comment:
      "Kyrve bytecode lock. GENERATED by `pnpm verify:midnight-bytecode --write`. Meaningful only " +
      "because the pinned profile sets bytecode_hash = none, which strips metadata and makes " +
      "compiled output a pure function of source, compiler and settings.",
    release: vendor.release,
    commit: vendor.commit,
    compiler: vendor.compiler,
    contracts,
  };
}

function main(): void {
  run("forge", ["build"]);
  const current = build();

  if (process.argv.includes("--write")) {
    writeFileSync(LOCK_PATH, stableStringify(current));
    console.log(`bytecode lock written: ${Object.keys(current.contracts).length} contracts`);
    for (const [name, entry] of Object.entries(current.contracts)) {
      console.log(
        `  ${name.padEnd(24)} runtime ${entry.runtimeSizeBytes} bytes  ${entry.runtimeCodeHash.slice(0, 16)}`,
      );
    }
    return;
  }

  if (!existsSync(LOCK_PATH)) {
    console.error("bytecode lock missing. Generate it with: pnpm verify:midnight-bytecode --write");
    process.exitCode = 1;
    return;
  }

  const expected = readJson<BytecodeLock>(LOCK_PATH);
  const failures: string[] = [];

  if (current.commit !== expected.commit) {
    failures.push(`vendored commit changed: ${expected.commit} -> ${current.commit}`);
  }
  for (const [key, value] of Object.entries(expected.compiler)) {
    if (JSON.stringify(current.compiler[key]) !== JSON.stringify(value)) {
      failures.push(
        `compiler ${key} changed: ${JSON.stringify(value)} -> ${JSON.stringify(current.compiler[key])}`,
      );
    }
  }
  for (const [name, entry] of Object.entries(expected.contracts)) {
    const actual = current.contracts[name];
    if (actual === undefined) {
      failures.push(`${name} is no longer compiled`);
      continue;
    }
    if (actual.runtimeCodeHash !== entry.runtimeCodeHash) {
      failures.push(
        `${name} runtime bytecode changed: ${entry.runtimeCodeHash} -> ${actual.runtimeCodeHash}. ` +
          "Recompilation is reproducible under bytecode_hash = none, so this means the source, the " +
          "compiler or the settings changed.",
      );
    }
  }

  // Cross-check against the chain when a local deployment exists.
  const manifestPath = repoPath("deployments/local/manifest.json");
  if (existsSync(manifestPath)) {
    const manifest = readJson<{ contracts: Record<string, { runtimeBytecodeHash: string }> }>(
      manifestPath,
    );
    const deployed = manifest.contracts["Midnight"]?.runtimeBytecodeHash;
    if (deployed !== undefined) {
      console.log(`  deployed Midnight runtime keccak (from manifest): ${deployed}`);
    }
  }

  if (failures.length > 0) {
    console.error("verify:midnight-bytecode FAILED\n");
    for (const failure of failures) console.error(`  - ${failure}`);
    process.exitCode = 1;
    return;
  }

  console.log("verify:midnight-bytecode PASS");
  console.log(`  release ${current.release} @ ${current.commit}`);
  for (const [name, entry] of Object.entries(current.contracts)) {
    console.log(
      `  ${name.padEnd(24)} ${entry.runtimeSizeBytes} bytes  ${entry.runtimeCodeHash.slice(0, 16)}`,
    );
  }
}

main();
