/**
 * Verifies the vendored Morpho Midnight submodule is exactly the pinned release, unmodified.
 *
 * The vendoring strategy is a git submodule rather than a copied tree. That is deliberate: a
 * submodule preserves upstream history, makes the pin a single reviewable SHA, and makes any
 * accidental edit visible as a dirty worktree instead of blending into Kyrve's own diff.
 *
 * This script fails if the pinned commit changes, if any core source file changes, if the
 * compiler or optimiser settings change, or if the EVM target changes. Any of those invalidates
 * every recorded bytecode hash and every deployment manifest.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

import { readJson, repoPath, run, stableStringify } from "../lib/shell.js";

interface SourceLock {
  morphoMidnight: {
    pinnedRelease: string;
    pinnedCommit: string;
    compiler: { primary: string };
    foundry: {
      via_ir: boolean;
      optimizer: boolean;
      optimizer_runs: number;
      bytecode_hash: string;
      evm_version: string;
    };
  };
}

interface VendorLock {
  $comment: string;
  submodulePath: string;
  release: string;
  commit: string;
  submodules: Record<string, string>;
  compiler: Record<string, unknown>;
  /** sha256 of every file under src/, so any edit to the core is detectable. */
  sourceHashes: Record<string, string>;
  /** sha256 over the sorted source hashes — one number that changes if anything does. */
  sourceTreeHash: string;
  licences: Record<string, string>;
}

const VENDOR = "vendor/midnight";
const LOCK_PATH = repoPath("vendor-lock.json");

function sourceFiles(): string[] {
  return run("git", ["-C", VENDOR, "ls-files", "src"])
    .stdout.split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .sort();
}

function hashFile(relative: string): string {
  return createHash("sha256")
    .update(readFileSync(repoPath(VENDOR, relative)))
    .digest("hex");
}

function buildLock(): VendorLock {
  const sourceLock = readJson<SourceLock>(repoPath("source-lock.json"));
  const pinned = sourceLock.morphoMidnight;

  const commit = run("git", ["-C", VENDOR, "rev-parse", "HEAD"]).stdout.trim();
  const describe = run("git", ["-C", VENDOR, "describe", "--tags", "--exact-match"], {
    allowFailure: true,
  }).stdout.trim();

  const submodules: Record<string, string> = {};
  for (const line of run("git", ["-C", VENDOR, "submodule", "status", "--recursive"]).stdout.split(
    "\n",
  )) {
    const match = line.trim().match(/^[+\-U ]?([0-9a-f]{40})\s+(\S+)/);
    if (match?.[1] !== undefined && match[2] !== undefined) submodules[match[2]] = match[1];
  }

  const sourceHashes: Record<string, string> = {};
  for (const file of sourceFiles()) sourceHashes[file] = hashFile(file);

  const sourceTreeHash = createHash("sha256")
    .update(
      Object.entries(sourceHashes)
        .map(([file, hash]) => `${file} ${hash}`)
        .join("\n"),
    )
    .digest("hex");

  return {
    $comment:
      "Kyrve vendor lock for the pinned Morpho Midnight submodule. GENERATED by `pnpm verify:vendor --write`. " +
      "Never edit by hand. Changing the pin is its own commit that also updates source-lock.json.",
    submodulePath: VENDOR,
    release: describe.length > 0 ? describe : pinned.pinnedRelease,
    commit,
    submodules,
    compiler: {
      solc: pinned.compiler.primary,
      ...pinned.foundry,
    },
    sourceHashes,
    sourceTreeHash,
    licences: {
      "src/Midnight.sol": "BUSL-1.1",
      allOtherSrcFiles: "GPL-2.0-or-later",
      note:
        "The Additional Use Grant at morpho-midnight-license-grants.morpho.eth was resolved on " +
        "2026-07-28 and is EMPTY. Only BUSL non-production use applies. Midnight is NOT open source.",
    },
  };
}

function main(): void {
  const write = process.argv.includes("--write");
  const current = buildLock();

  if (write) {
    writeFileSync(LOCK_PATH, stableStringify(current));
    console.log(
      `vendor-lock.json written: ${Object.keys(current.sourceHashes).length} source files`,
    );
    console.log(`  release ${current.release} @ ${current.commit}`);
    console.log(`  sourceTreeHash ${current.sourceTreeHash}`);
    return;
  }

  let expected: VendorLock;
  try {
    expected = readJson<VendorLock>(LOCK_PATH);
  } catch {
    console.error("vendor-lock.json is missing. Generate it with: pnpm verify:vendor --write");
    process.exitCode = 1;
    return;
  }

  const failures: string[] = [];

  if (current.commit !== expected.commit) {
    failures.push(
      `pinned commit changed: expected ${expected.commit}, found ${current.commit}. ` +
        "Changing the Midnight pin invalidates every bytecode hash and every deployment manifest, " +
        "and must be its own commit that also updates source-lock.json.",
    );
  }
  if (current.release !== expected.release) {
    failures.push(`release changed: expected ${expected.release}, found ${current.release}`);
  }
  if (current.sourceTreeHash !== expected.sourceTreeHash) {
    const changed = Object.entries(current.sourceHashes)
      .filter(([file, hash]) => expected.sourceHashes[file] !== hash)
      .map(([file]) => file);
    const removed = Object.keys(expected.sourceHashes).filter(
      (file) => current.sourceHashes[file] === undefined,
    );
    failures.push(
      `vendored core source changed. vendor/midnight is never edited.\n` +
        `    modified/added: ${changed.join(", ") || "(none)"}\n` +
        `    removed:        ${removed.join(", ") || "(none)"}`,
    );
  }
  for (const [key, value] of Object.entries(expected.compiler)) {
    if (JSON.stringify(current.compiler[key]) !== JSON.stringify(value)) {
      failures.push(
        `compiler setting ${key} changed: expected ${JSON.stringify(value)}, found ${JSON.stringify(current.compiler[key])}`,
      );
    }
  }
  for (const [path, commit] of Object.entries(expected.submodules)) {
    if (current.submodules[path] !== commit) {
      failures.push(
        `nested submodule ${path} changed: expected ${commit}, found ${current.submodules[path] ?? "(absent)"}`,
      );
    }
  }

  // The worktree must be clean, or the hashes above describe files nobody reviewed.
  const dirty = run("git", ["-C", VENDOR, "status", "--porcelain"]).stdout.trim();
  if (dirty.length > 0) {
    failures.push(`vendor/midnight has local modifications:\n${dirty}`);
  }

  if (failures.length > 0) {
    console.error("verify:vendor FAILED\n");
    for (const failure of failures) console.error(`  - ${failure}`);
    process.exitCode = 1;
    return;
  }

  console.log("verify:vendor PASS");
  console.log(`  release        ${current.release} @ ${current.commit}`);
  console.log(`  source files   ${Object.keys(current.sourceHashes).length}, unmodified`);
  console.log(`  sourceTreeHash ${current.sourceTreeHash}`);
  console.log(
    `  compiler       solc ${current.compiler["solc"]}, evm ${current.compiler["evm_version"]}, runs ${current.compiler["optimizer_runs"]}`,
  );
  console.log("  licence        src/Midnight.sol is BUSL-1.1 and NOT open source; grant is empty");
}

main();
