// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity 0.8.34;

import {Script} from "forge-std/Script.sol";

import {Market, Offer} from "midnight/interfaces/IMidnight.sol";

import {LocalMidnightFixture} from "../integration/LocalMidnightFixture.sol";

/// @dev Emits real market structs alongside the ids `touchMarket` actually returned, plus a real
/// offer alongside its `keccak256(abi.encode(offer))`.
///
/// This is what pins `packages/midnight`'s id and hash derivation to reality. `IdLib.toId` is a
/// CREATE2 address hash of an SSTORE2 deployment, not the obvious `keccak256(abi.encode(market))`,
/// and a transcription error there would silently produce ids that match nothing on chain.
///
/// Run: forge script contracts/script/ExportMarketFixtures.s.sol
contract ExportMarketFixtures is Script {
    string internal constant OUT = "./packages/midnight/test/fixtures/markets.json";
    string internal constant OBJ = "kyrve.marketFixture";

    uint256 internal constant ANCHOR = 1_800_000_000;

    function run() external {
        vm.warp(ANCHOR);

        LocalMidnightFixture fixtureContract = new LocalMidnightFixture();
        fixtureContract.deploy(ANCHOR);

        string[] memory encodedMarkets = new string[](4);
        string[] memory ids = new string[](4);
        string[] memory keys = new string[](4);

        for (uint256 i = 0; i < 4; i++) {
            Market memory m = fixtureContract.market(i);
            encodedMarkets[i] = vm.toString(abi.encode(m));
            ids[i] = vm.toString(fixtureContract.marketId(i));
            keys[i] = fixtureContract.marketKeys(i);
        }

        // A complete, realistic offer so the offer-hash derivation is pinned too.
        Offer memory offer = Offer({
            market: fixtureContract.market(1),
            buy: true,
            maker: address(0xA11CE),
            start: ANCHOR,
            expiry: ANCHOR + 3600,
            tick: 6000,
            group: keccak256("kyrve.quote.fixture"),
            callback: address(0xCA11BAC4),
            callbackData: abi.encode(keccak256("kyrve.quote.fixture")),
            receiverIfMakerIsSeller: address(0),
            ratifier: address(0x4A71F1E4),
            reduceOnly: false,
            maxUnits: 1_000_000e6,
            maxAssets: 0,
            continuousFeeCap: type(uint256).max
        });

        vm.serializeString(
            OBJ,
            "$comment",
            "GENERATED by contracts/script/ExportMarketFixtures.s.sol. Market ids are what touchMarket actually returned."
        );
        vm.serializeString(OBJ, "anchor", vm.toString(ANCHOR));
        vm.serializeString(OBJ, "chainId", vm.toString(block.chainid));
        vm.serializeString(OBJ, "midnight", vm.toString(address(fixtureContract.midnight())));
        vm.serializeString(OBJ, "marketKeys", keys);
        vm.serializeString(OBJ, "encodedMarkets", encodedMarkets);
        vm.serializeString(OBJ, "encodedOffer", vm.toString(abi.encode(offer)));
        vm.serializeString(OBJ, "offerHash", vm.toString(keccak256(abi.encode(offer))));

        string memory out = vm.serializeString(OBJ, "marketIds", ids);
        vm.writeJson(out, OUT);
    }
}
