// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity 0.8.34;

import {Script} from "forge-std/Script.sol";

import {IMidnight, Market, Offer} from "midnight/interfaces/IMidnight.sol";
import {TickLib} from "midnight/libraries/TickLib.sol";
import {UtilsLib} from "midnight/libraries/UtilsLib.sol";
import {WAD, ORACLE_PRICE_SCALE} from "midnight/libraries/ConstantsLib.sol";

import {LocalMidnightFixture} from "../integration/LocalMidnightFixture.sol";
import {KyrveExactFillVault} from "../integration/KyrveExactFillVault.sol";
import {KyrveQuoteRatifier} from "../integration/KyrveQuoteRatifier.sol";
import {ActivatedQuote, QuoteStatus} from "../integration/KyrveQuoteBinding.sol";

/// @dev Records the return values of REAL `take` calls against real unmodified Midnight, so
/// `packages/quote-math` can be differentially tested against actual settlement rather than
/// against a restatement of the same formula.
///
/// This is the difference between "our TypeScript agrees with our Solidity" and "our TypeScript
/// agrees with what the protocol actually pays". Only the second is worth anything.
///
/// Every numeric value is a decimal STRING: JSON numbers are IEEE-754 doubles and would lose
/// precision above 2^53.
///
/// Run: forge script contracts/script/ExportTakeFixtures.s.sol
contract ExportTakeFixtures is Script {
    using UtilsLib for uint256;

    string internal constant OUT = "./packages/quote-math/test/fixtures/take-results.json";
    string internal constant OBJ = "kyrve.takeFixture";

    /// @dev Anchored rather than read from the clock, so the fixture is byte-stable across runs.
    uint256 internal constant ANCHOR = 1_800_000_000;

    LocalMidnightFixture internal fixtureContract;
    IMidnight internal midnight;
    address internal constant BORROWER = address(0xB0770E4);
    /// @dev Explicit, because Foundry forbids relying on a script contract's own address.
    address internal constant ACTIVATOR = address(0xAC71A70);
    uint256 internal nonce;

    function run() external {
        vm.warp(ANCHOR);

        fixtureContract = new LocalMidnightFixture();
        fixtureContract.deploy(ANCHOR);
        midnight = IMidnight(address(fixtureContract.midnight()));

        uint256[6] memory ticks = [uint256(4400), 4912, 5424, 5936, 6448, 6744];
        uint256[3] memory unitAmounts = [uint256(1_000e6), 250_000e6, 1_000_000e6];

        uint256 rowCount = ticks.length * unitAmounts.length * 2;
        string[] memory rows = new string[](rowCount);

        uint256 r;
        // Market 0 is the 30-day maturity, market 1 the 90-day, so both settlement-fee
        // interpolation brackets are exercised.
        for (uint256 m = 0; m < 2; m++) {
            for (uint256 i = 0; i < ticks.length; i++) {
                for (uint256 j = 0; j < unitAmounts.length; j++) {
                    rows[r++] = _row(m, ticks[i], unitAmounts[j]);
                }
            }
        }

        vm.serializeString(
            OBJ,
            "$comment",
            "GENERATED by contracts/script/ExportTakeFixtures.s.sol from REAL take() returns against unmodified Midnight. Do not edit by hand."
        );
        vm.serializeString(OBJ, "midnightCommit", "dbd8d3d54d324a03df9f06d3c77d50a7bd1e09a0");
        vm.serializeString(OBJ, "anchor", vm.toString(ANCHOR));
        string memory out = vm.serializeString(OBJ, "rows", rows);
        vm.writeJson(out, OUT);
    }

    /// @dev One real settlement, serialised as a compact pipe-delimited record:
    /// tick|units|secondsToMaturity|feeCbp0..6|buyerAssets|sellerAssets|pendingFeeIncrease
    function _row(uint256 marketIndex, uint256 tick, uint256 units) internal returns (string memory) {
        Market memory market = fixtureContract.market(marketIndex);
        bytes32 marketId = fixtureContract.marketId(marketIndex);

        nonce++;
        bytes32 quoteId = keccak256(abi.encode("kyrve.fixture", nonce));

        KyrveExactFillVault vault = new KyrveExactFillVault(address(midnight), ACTIVATOR);
        KyrveQuoteRatifier ratifier = new KyrveQuoteRatifier(address(midnight), address(vault));
        vm.prank(ACTIVATOR);
        vault.authoriseRatifier(address(ratifier), true);

        uint128 expected = uint128(units.mulDivDown(TickLib.tickToPrice(tick), WAD));

        Offer memory offer = Offer({
            market: market,
            buy: true,
            maker: address(vault),
            start: block.timestamp,
            expiry: block.timestamp + 1 hours,
            tick: tick,
            group: quoteId,
            callback: address(vault),
            callbackData: abi.encode(quoteId),
            receiverIfMakerIsSeller: address(0),
            ratifier: address(ratifier),
            reduceOnly: false,
            maxUnits: uint128(units),
            maxAssets: 0,
            continuousFeeCap: type(uint256).max
        });

        vm.prank(ACTIVATOR);
        vault.activateQuote(
            quoteId,
            ActivatedQuote({
                offerHash: keccak256(abi.encode(offer)),
                marketId: marketId,
                taker: BORROWER,
                exactUnits: uint128(units),
                expectedBuyerAssets: expected,
                maxPendingFee: type(uint128).max,
                expiry: uint40(block.timestamp + 1 hours),
                status: QuoteStatus.Executable
            })
        );

        fixtureContract.usdc().mint(address(vault), expected);

        uint256 collateral = units.mulDivUp(WAD, fixtureContract.LLTV_WETH()).mulDivUp(
            ORACLE_PRICE_SCALE, fixtureContract.wethOracle().price()
        );
        fixtureContract.weth().mint(BORROWER, collateral);

        vm.startPrank(BORROWER);
        fixtureContract.weth().approve(address(midnight), collateral);
        midnight.supplyCollateral(market, 0, collateral, BORROWER);
        (uint256 buyerAssets, uint256 sellerAssets) =
            midnight.take(offer, hex"", units, BORROWER, BORROWER, address(0), hex"");
        vm.stopPrank();

        uint256 secondsToMaturity = market.maturity - block.timestamp;

        string memory record = string.concat(
            vm.toString(tick), "|", vm.toString(units), "|", vm.toString(secondsToMaturity), "|"
        );
        for (uint256 i = 0; i < 7; i++) {
            record = string.concat(record, vm.toString(uint256(fixtureContract.feeCbp(i))), ",");
        }
        return string.concat(
            record,
            "|",
            vm.toString(buyerAssets),
            "|",
            vm.toString(sellerAssets),
            "|",
            vm.toString(uint256(midnight.pendingFee(marketId, address(vault))))
        );
    }
}
