// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity 0.8.34;

import {Script} from "forge-std/Script.sol";

import {TickLib, MAX_TICK, PRICE_ROUNDING_STEP, LN_ONE_PLUS_DELTA} from "midnight/libraries/TickLib.sol";
import {
    WAD,
    CBP,
    DEFAULT_TICK_SPACING,
    CALLBACK_SUCCESS,
    MAX_CONTINUOUS_FEE,
    maxSettlementFee
} from "midnight/libraries/ConstantsLib.sol";

/// @dev Emits the differential fixture that pins Kyrve's TypeScript quote math to the pinned
/// Midnight release.
///
/// The fixture is generated FROM the vendored Solidity, never hand-written, so it cannot drift
/// from the release without `pnpm verify:generated` noticing. `packages/quote-math` then asserts
/// bit-for-bit equality at every one of the 6,745 ticks in range.
///
/// `vendor/midnight/test/ticks_exact.json` is NOT usable for this purpose: it is a mathematically
/// exact reference that Midnight's own tests compare its Taylor approximation against within a
/// 2 bps tolerance. Kyrve needs the approximation itself, exactly.
///
/// Every value is serialised as a decimal STRING. JSON numbers are IEEE-754 doubles and would
/// silently lose precision above 2^53.
///
/// Run: forge script contracts/script/ExportQuoteMathFixtures.s.sol
contract ExportQuoteMathFixtures is Script {
    string internal constant OUT = "./packages/quote-math/test/fixtures/tick-prices.json";
    string internal constant OBJ = "kyrve.quoteMathFixture";

    function run() external {
        string[] memory tickPrices = new string[](MAX_TICK + 1);
        for (uint256 tick = 0; tick <= MAX_TICK; tick++) {
            tickPrices[tick] = vm.toString(TickLib.tickToPrice(tick));
        }

        string[] memory maxFees = new string[](7);
        for (uint256 i = 0; i < 7; i++) {
            maxFees[i] = vm.toString(maxSettlementFee(i));
        }

        vm.serializeString(
            OBJ,
            "$comment",
            "GENERATED by contracts/script/ExportQuoteMathFixtures.s.sol from the pinned Midnight release. Do not edit by hand."
        );
        vm.serializeString(OBJ, "midnightRelease", "2026-07-23");
        vm.serializeString(OBJ, "midnightCommit", "dbd8d3d54d324a03df9f06d3c77d50a7bd1e09a0");
        vm.serializeString(OBJ, "wad", vm.toString(WAD));
        vm.serializeString(OBJ, "cbp", vm.toString(CBP));
        vm.serializeString(OBJ, "maxTick", vm.toString(MAX_TICK));
        vm.serializeString(OBJ, "priceRoundingStep", vm.toString(PRICE_ROUNDING_STEP));
        vm.serializeString(OBJ, "lnOnePlusDelta", vm.toString(LN_ONE_PLUS_DELTA));
        vm.serializeString(OBJ, "defaultTickSpacing", vm.toString(uint256(DEFAULT_TICK_SPACING)));
        vm.serializeString(OBJ, "maxContinuousFee", vm.toString(uint256(MAX_CONTINUOUS_FEE)));
        vm.serializeString(OBJ, "callbackSuccess", vm.toString(CALLBACK_SUCCESS));
        vm.serializeString(OBJ, "maxSettlementFee", maxFees);

        string memory out = vm.serializeString(OBJ, "tickPrices", tickPrices);
        vm.writeJson(out, OUT);
    }
}
