/**
 * Generates the six Phase 6 operational role keys.
 *
 * ════════════════════════════════════════════════════════════════════════════════════════════
 * WHAT THIS IS FOR
 * ════════════════════════════════════════════════════════════════════════════════════════════
 *
 * Phase 5 deployed to Sepolia with the keeper, the operator, the curator and the residue
 * beneficiary all set to the deployer's address. Separating them is a deployment, and a deployment
 * needs six addresses that do not exist yet. This mints them.
 *
 * It does NOT touch `DEPLOYER_PRIVATE_KEY`. The deployer is the owner's existing wallet, it is the
 * only role that already holds testnet ETH, and a script that could regenerate it would be a script
 * that could strand the whole deployment.
 *
 * ════════════════════════════════════════════════════════════════════════════════════════════
 * TESTNET ONLY, AND SAY SO
 * ════════════════════════════════════════════════════════════════════════════════════════════
 *
 * These keys land in `.env` in plaintext, which is where this repository already keeps the deployer
 * key and the dust wallets. That is acceptable for Ethereum Sepolia and is acceptable for nothing
 * else. A production Kyrve deployment gives the emergency authority and the curator to hardware or
 * multisig accounts, and `docs/phase6/ROLES.md` records that as the intended end state rather than
 * pretending this script produces it.
 *
 * The keeper is the exception worth naming: it signs constantly, it cannot be a cold key, and its
 * blast radius is bounded on purpose — it advances computation and can neither choose inputs nor
 * change outcomes. That bound is what makes a hot keeper key acceptable at all.
 *
 * ════════════════════════════════════════════════════════════════════════════════════════════
 * KEY HANDLING
 * ════════════════════════════════════════════════════════════════════════════════════════════
 *
 * Addresses only, ever, in every line of output. A private key is never echoed — not in full, not
 * truncated. Existing entries are never overwritten: a regenerated key over a funded address
 * strands the funds and, worse, silently changes who a deployed contract's `immutable` refers to.
 */

import { appendFileSync } from "node:fs";

import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

import { loadEnv } from "../lib/env.js";
import { keyVariableFor, ROLE_ORDER, type RoleName } from "../lib/roles.js";
import { repoPath } from "../lib/shell.js";

/** Every role except the deployer, which is the owner's existing wallet and is never generated. */
const GENERATED: readonly RoleName[] = ROLE_ORDER.filter((role) => role !== "deployer");

function main(): void {
  loadEnv();

  const existing: RoleName[] = [];
  const missing: RoleName[] = [];
  for (const role of GENERATED) {
    const value = (process.env[keyVariableFor(role)] ?? "").trim();
    if (value.length > 0) existing.push(role);
    else missing.push(role);
  }

  if (existing.length > 0) {
    console.log("\nroles already present in .env — not regenerating\n");
    for (const role of existing) {
      const key = (process.env[keyVariableFor(role)] ?? "").trim() as `0x${string}`;
      console.log(`  ${role.padEnd(20)} ${privateKeyToAccount(key).address}`);
    }
    console.log();
  }

  if (missing.length === 0) {
    console.log("  every operational role already has a key. Nothing to do.\n");
    console.log("  Run `pnpm roles:status` to see addresses, balances and account kind.\n");
    return;
  }

  const lines: string[] = [
    "",
    "# ── Phase 6 operational roles ───────────────────────────────────────────────────────────",
    "# Generated by `pnpm roles:generate`. TESTNET ONLY — these are plaintext keys on this",
    "# machine. `KyrveRoleRegistry` refuses a deployment in which any two of them coincide, and",
    "# `scripts/lib/roles.ts` refuses one before a transport is even built.",
    "# Authority per role: docs/phase6/ROLES.md. Never fund these on a network where ETH is worth",
    "# anything.",
  ];

  const minted: { readonly role: RoleName; readonly address: string }[] = [];
  for (const role of missing) {
    const key = generatePrivateKey();
    const { address } = privateKeyToAccount(key);
    lines.push(`${keyVariableFor(role)}=${key}`);
    minted.push({ role, address });
  }
  lines.push("");

  appendFileSync(repoPath(".env"), `${lines.join("\n")}\n`, "utf8");

  console.log("minted, and appended to .env (git-ignored):\n");
  for (const { role, address } of minted) {
    console.log(`  ${role.padEnd(20)} ${address}`);
  }
  console.log(
    "\n  Next: `pnpm roles:status` to see which of these need gas, then fund the signing\n" +
      "  roles from a faucet or with `pnpm roles:fund`.\n",
  );
}

main();
