/**
 * Generates throwaway Sepolia funding wallets.
 *
 * ════════════════════════════════════════════════════════════════════════════════════════════
 * WHAT THIS IS FOR
 * ════════════════════════════════════════════════════════════════════════════════════════════
 *
 * Sepolia faucets rate-limit per address — typically around 0.05 ETH per address per day — and the
 * Phase 3 gate has exactly one SKIP: a real curve epoch needs ~0.0236 ETH and the deployer holds
 * 0.0041. Claiming into several fresh addresses and consolidating is the ordinary way round that.
 *
 * These wallets are **disposable funding plumbing**. They hold testnet ETH for minutes, they are
 * swept to the deployer by `scripts/dust/sweep.ts`, and nothing else in this repository reads them.
 *
 * ════════════════════════════════════════════════════════════════════════════════════════════
 * TESTNET ONLY, AND STRUCTURALLY SO
 * ════════════════════════════════════════════════════════════════════════════════════════════
 *
 * `sweep.ts` hardcodes Ethereum Sepolia and refuses any other chain id. That is deliberate: a
 * sweep script is a "send everything to one address" primitive, and the only safe version of that
 * is one that cannot be pointed at a network where the balance is worth something. **Do not fund
 * these addresses on mainnet.** If real value ever lands on one, the key is in a plaintext local
 * file and should be treated as compromised.
 *
 * ════════════════════════════════════════════════════════════════════════════════════════════
 * KEY HANDLING
 * ════════════════════════════════════════════════════════════════════════════════════════════
 *
 * Keys are appended to `.env`, which is git-ignored and is already where this repository keeps the
 * deployer key. They are added to the secret scan's SENSITIVE list in the same commit, so if one
 * ever reaches a tracked file `pnpm verify:secrets` fails.
 *
 * This script prints **addresses only**. A private key is never echoed — not in full, not
 * truncated — matching `scripts/lib/env.ts`, which returns the derived address and never a signer.
 */

import { appendFileSync, readFileSync } from "node:fs";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

import { loadEnv } from "../lib/env.js";
import { repoPath } from "../lib/shell.js";

const DEFAULT_COUNT = 3;
const PREFIX = "DUST_PRIVATE_KEY_";

/** `sweep.ts` scans this many slots, so nothing beyond it would ever be swept. */
const MAX_WALLETS = 10;

function main(): void {
  loadEnv();
  const count = Number.parseInt(process.argv[2] ?? String(DEFAULT_COUNT), 10);
  if (!Number.isInteger(count) || count < 1 || count > MAX_WALLETS) {
    throw new Error(
      `count must be an integer between 1 and ${MAX_WALLETS}, received ${process.argv[2]}`,
    );
  }

  /**
   * APPENDS, never overwrites, and the distinction is the whole safety property.
   *
   * A regenerated key over a funded address strands the funds, and the failure mode is silent — the
   * address in the faucet's history simply stops being one we hold. So `count` is how many NEW
   * wallets to add, and they take the first free slots above whatever already exists rather than
   * slots 1..count. The earlier version refused outright when any of 1..count was taken, which was
   * safe and also made "give me four more" impossible without hand-editing `.env`.
   */
  const occupied: number[] = [];
  for (let i = 1; i <= MAX_WALLETS; i += 1) {
    if ((process.env[`${PREFIX}${i}`] ?? "").trim().length > 0) occupied.push(i);
  }

  const free: number[] = [];
  for (let i = 1; i <= MAX_WALLETS && free.length < count; i += 1) {
    if (!occupied.includes(i)) free.push(i);
  }
  if (free.length < count) {
    throw new Error(
      `only ${free.length} of the ${MAX_WALLETS} dust slots are free and ${count} were asked for. ` +
        "Sweep and remove some DUST_PRIVATE_KEY_* lines from .env first — `pnpm dust:sweep` moves " +
        "their balances to the deployer before anything is discarded.",
    );
  }

  if (occupied.length > 0) {
    console.log(`${occupied.length} dust wallet(s) already exist and are left untouched:\n`);
    for (const i of occupied) {
      const key = (process.env[`${PREFIX}${i}`] ?? "").trim() as `0x${string}`;
      console.log(`  ${PREFIX}${i}  ${privateKeyToAccount(key).address}`);
    }
    console.log("");
  }

  const lines: string[] = [
    "",
    "# ── Disposable Sepolia funding wallets ──────────────────────────────────────────────────",
    "# Generated by `pnpm dust:generate`. TESTNET ONLY — `pnpm dust:sweep` hardcodes Sepolia and",
    "# refuses every other chain. Fund from a faucet, sweep to the deployer, forget. Never fund",
    "# these on mainnet: the keys are in plaintext on this machine.",
  ];

  console.log(`dust wallets — ${count} NEW disposable Sepolia funding address(es)\n`);
  for (const i of free) {
    const key = generatePrivateKey();
    const address = privateKeyToAccount(key).address;
    lines.push(`${PREFIX}${i}=${key}`);
    console.log(`  ${PREFIX}${i}  ${address}`);
  }
  appendFileSync(repoPath(".env"), `${lines.join("\n")}\n`);

  // Confirm .env is genuinely ignored before claiming the keys are safely stored.
  const gitignore = readFileSync(repoPath(".gitignore"), "utf8");
  const ignored = gitignore.includes("\n.env\n") || gitignore.startsWith(".env\n");
  console.log(`\n  keys written to .env  (git-ignored: ${ignored})`);
  if (!ignored) {
    console.error("\n  REFUSE TO PROCEED: .env is not git-ignored. Remove the keys immediately.\n");
    process.exitCode = 1;
    return;
  }

  console.log("\n  Next:");
  console.log(
    "    1. Send Sepolia ETH to the addresses above (a faucet each, or one transfer each).",
  );
  console.log("    2. pnpm dust:sweep            — read-only, shows what it would move.");
  console.log(
    "    3. DEPLOY_SEPOLIA=true KYRVE_CONFIRM_BROADCAST=true pnpm dust:sweep --execute\n",
  );
}

main();
